### ISSUE TITLE
Swagger failed to load after using joi lazy(fn)

### ISSUE THREAD

**Issue by ganeshkharche12** [lightsofapollo/joi-to-json-schema#36]
Using JOI validation with lazy(fn) to check recursive validation. In this case swagger failed to load routes even all routes are working. Below are all the generated logs.

> Failed to build API documentation for "/Demo"!
This is likely a bug in your Foxx service.
Check the route methods you are using to document your API. via Error: sorry, do not know how to convert unknown joi type: "lazy" 
at convert (/usr/share/arangodb3/js/node/node_modules/joi-to-json-schema/build/index.js:186:11)
at Array.forEach (native)
at Object.array (/usr/share/arangodb3/js/node/node_modules/joi-to-json-schema/build/index.js:87:14)
at convert (/usr/share/arangodb3/js/node/node_modules/joi-to-json-schema/build/index.js:225:32)
at /usr/share/arangodb3/js/node/node_modules/joi-to-json-schema/build/index.js:167:43
at Array.forEach (native)
at Object.object (/usr/share/arangodb3/js/node/node_modules/joi-to-json-schema/build/index.js:165:25)
at joi2schema (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/swagger-context.js:568:10)

i already had opened this issue on github ArangoDB issues 
https://github.com/arangodb/arangodb/issues/6132

**Comment by lightsofapollo** [comment]
Yeah all but certain lazy was not a thing when we wrote the initial version. I will take a look but this is an area where we could honestly use some help.

**Comment by jeremymelchor** [comment]
Hi, any news on this issue ?
